classdef TDAirwaySkeleton < TDPlugin
    % TDAirwaySkeleton. Plugin for skeletonising the pulmonary airway tree.
    %
    %     This is a plugin for the Pulmonary Toolkit. Plugins can be run using 
    %     the gui, or through the interfaces provided by the Pulmonary Toolkit.
    %     See TDPlugin.m for more information on how to run plugins.
    %
    %     Plugins should not be run directly from your code.
    %
    %     TDAirwaySkeleton calls the TDAirways plugin to segment the airway
    %     tree. It then uses the TDSkeletonise library routine to reduce the
    %     airway tree to a skeleton. The results are stored in a heirarchical
    %     tree structure.
    %
    %     The output image generated by GenerateImageFromResults creates a
    %     colour-coded segmentation image showing skeleton points as colour 1,
    %     bifurcation points as 3 and removed internal loop points as 6.
    %
    %
    %     Licence
    %     -------
    %     Part of the TD Pulmonary Toolkit. http://code.google.com/p/pulmonarytoolkit
    %     Author: Tom Doel, 2012.  www.tomdoel.com
    %     Distributed under the GNU GPL v3 licence. Please see website for details.
    %    
    
    
    
    properties
        ButtonText = 'Airway <BR>Centreline'
        ToolTip = 'Show airway skeletonisation results processed globally'
        Category = 'Airways'

        AllowResultsToBeCached = true
        AlwaysRunPlugin = false
        PluginType = 'ReplaceOverlay'
        HidePluginInDisplay = false
        FlattenPreviewImage = true
        TDPTKVersion = '1'
        ButtonWidth = 6
        ButtonHeight = 2
        GeneratePreview = true
    end
    
    methods (Static)
        function results = RunPlugin(dataset, reporting)
            lung_image = dataset.GetResult('TDLungROI');
            airway_results = dataset.GetResult('TDAirways');
            results = TDGetCentrelineFromAirways(lung_image, airway_results, reporting);
        end

        function results = GenerateImageFromResults(skeleton_results, image_templates, ~)
            template_image = image_templates.GetTemplateImage(TDContext.LungROI);

            new_image = zeros(template_image.ImageSize, 'uint8');
            new_image(template_image.GlobalToLocalIndices(skeleton_results.OriginalSkeletonPoints)) = 2;
            new_image(template_image.GlobalToLocalIndices(skeleton_results.SkeletonPoints)) = 1;
            new_image(template_image.GlobalToLocalIndices(skeleton_results.RemovedPoints)) = 6;
            new_image(template_image.GlobalToLocalIndices(skeleton_results.BifurcationPoints)) = 3;
            
            results = template_image.BlankCopy;
            results.ChangeRawImage(new_image);
            results.ImageType = TDImageType.Colormap;
            
            results.SetVoxelToThis(skeleton_results.StartPoint, 4);
            
        end
    end
end
